# Generated by Django 4.0.1 on 2022-02-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CPRS_admin", "0007_rename_supevisor_profile_supervisor_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_request",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="CPRS_admin.client",
            ),
        ),
    ]
