# Generated by Django 4.0.1 on 2022-01-21 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CPRS_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="group",
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(
                through="CPRS_admin.Test", to="CPRS_admin.Student"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="CPRS_admin.student"
            ),
        ),
        migrations.AddField(
            model_name="test",
            name="student_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="CPRS_admin.studentgroup",
            ),
        ),
    ]
