# Generated by Django 4.0.1 on 2022-01-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0002_student_is_active_alter_student_profile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
