# Generated by Django 4.0.1 on 2022-02-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CPRS_admin", "0002_student_profile_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="has_project",
            field=models.BooleanField(default=False),
        ),
    ]
