# Generated by Django 4.0.1 on 2022-01-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0002_test_remove_student_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('student', 'student_group')},
        ),
    ]
