# Generated by Django 4.0.1 on 2022-01-25 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0002_test_remove_student_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('student', 'student_group')},
        ),
        migrations.CreateModel(
            name='Recommended_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField()),
                ('client', models.ManyToManyField(to='CPRS_admin.Client')),
                ('group', models.ManyToManyField(to='CPRS_admin.StudentGroup')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CPRS_admin.project')),
            ],
        ),
    ]
