# Generated by Django 4.0.1 on 2022-01-25 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CPRS_admin", "0003_alter_test_unique_together_recommended_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="feedbacktitle",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="projectclientid",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="student_profile",
            old_name="studentaoi",
            new_name="area_of_interest",
        ),
        migrations.RenameField(
            model_name="student_profile",
            old_name="studentcgpa",
            new_name="cgpa",
        ),
        migrations.RenameField(
            model_name="student_profile",
            old_name="studentcourse",
            new_name="course_taken",
        ),
        migrations.RenameField(
            model_name="student_profile",
            old_name="studentname",
            new_name="skills",
        ),
        migrations.RenameField(
            model_name="student_profile",
            old_name="studentskills",
            new_name="specialization",
        ),
        migrations.RemoveField(
            model_name="project",
            name="projectassignedstatus",
        ),
        migrations.RemoveField(
            model_name="student_profile",
            name="studentspecialization",
        ),
        migrations.AddField(
            model_name="project",
            name="is_assigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="has_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="student",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="CPRS_admin.student",
            ),
        ),
        migrations.AlterField(
            model_name="supervisor",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
