# Generated by Django 4.0.1 on 2022-01-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0003_alter_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
