# Generated by Django 4.0.1 on 2022-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0004_remove_studentgroup_student_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_no',
            field=models.IntegerField(default=0),
        ),
    ]
