# Generated by Django 4.0.1 on 2022-01-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0004_rename_feedbacktitle_feedback_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedbackdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskprogress',
            new_name='progress',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskprojectid',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
