# Generated by Django 4.0.1 on 2022-01-25 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0005_rename_feedbackdescription_feedback_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='students',
            new_name='student',
        ),
    ]
