# Generated by Django 4.0.1 on 2022-01-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0006_rename_students_studentgroup_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='area_of_interest',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_taken',
        ),
        migrations.RemoveField(
            model_name='student',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='id',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='assigned_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CPRS_admin.studentgroup'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CPRS_admin.student'),
        ),
    ]
