# Generated by Django 4.0.1 on 2022-02-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0006_delete_client_type_project_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supevisor_Profile',
            new_name='Supervisor_Profile',
        ),
    ]
