# Generated by Django 4.0.1 on 2022-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CPRS_admin", "0006_alter_student_student_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_no",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
