# Generated by Django 4.0.1 on 2022-02-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0007_alter_student_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.TextField(null=True),
        ),
    ]
