# Generated by Django 4.0.1 on 2022-01-25 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CPRS_admin', '0007_remove_student_area_of_interest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectoverview',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projecttitle',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='cgpa',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
