# Generated by Django 4.0.1 on 2022-02-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CPRS_admin", "0008_alter_client_request_id_alter_project_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_request",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
