# Generated by Django 4.0.1 on 2022-02-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CPRS_admin", "0009_alter_client_request_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_request",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="CPRS_admin.studentgroup",
            ),
        ),
    ]
